// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using pruebaDesarrollador.Data;

#nullable disable

namespace pruebaDesarrollador.Migrations
{
    [DbContext(typeof(tazaDBContext))]
    [Migration("20231207202014_Initial Migration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("pruebaDesarrollador.Entity.Cotizador", b =>
                {
                    b.Property<int>("tazaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("tazaId"), 1L, 1);

                    b.Property<float>("MontoRecibir")
                        .HasColumnType("real");

                    b.Property<float>("valorRendimiento")
                        .HasColumnType("real");

                    b.HasKey("tazaId");

                    b.ToTable("Cotizador");
                });
#pragma warning restore 612, 618
        }
    }
}
